---
- name: cluster prepare
  hosts: all
  become: true
  tags:
    - all

  roles:
    - base_config
    - pcs_install
    - fence_agents

- name: cluster config
  hosts: pcs1
  become: true
  tags:
    - all

  roles:
    - pcs_config
...
