---

# echo 'y' | mkfs.gfs2 -j3 -p lock_dlm -t pcs_cluster:gfs2 /dev/cluster_vg/cluster_lv
# echo 'y' | mkfs.gfs2 -j2 -p lock_dlm -t otusha:gfs2 /dev/cluster_vg/cluster_lv
- name: Create a gfs2 filesystem on /dev/mapper/device and check disk blocks
  ansible.builtin.shell: "echo 'y' | mkfs.gfs2 -j2 -p lock_dlm -t {{ item.name }}:gfs2 {{ item.lv }}"
  with_items: 
    - { name: 'fileio_cluster', lv: '/dev/fileio_cluster_vg/file0_cluster_lv' }
    - { name: 'block_cluster', lv: '/dev/block_cluster_vg/block0_cluster_lv' }
    #- { name: 'ramdisk_cluster', lv: '/dev/ramdisk_cluster_vg/ram0_cluster_lv' }
