---
#- name: Debian OS
#  block:

#  - name: Install additional packages for lvm2
#    ansible.builtin.apt:
#      name:
#        - clvm
#      state: present

#  when: ansible_os_family == "Debian"

#- name: Redhat OS
#  block:

  ## dnf install iscsi-initiator-utils gfs2-utils lvm2-cluster
  #- name: Install additional packages for lvm2
  #  ansible.builtin.dnf:
  #    name:
  #      #- lvm2-cluster
  #      - lvm2
  #    state: present

  #when: ansible_os_family == "RedHat"



# pvcreate /dev/mapper/otusFileio
# pvcreate /dev/mapper/otusBlock
# pvcreate /dev/mapper/otusRamdisk
# vgcreate -Ay -cy fileio_cluster_vg /dev/mapper/otusFileio
# vgcreate -Ay -cy block_cluster_vg /dev/mapper/otusBlock
# vgcreate -Ay -cy ramdisk_cluster_vg /dev/mapper/otusRamdisk
- name: Create a volume groups
  community.general.lvg:
    #state: present
    vg: "{{ item.vg }}"
    pvs: "{{ item.pvs }}"
    #vg_options: "-Ay -cy" # "--autobackup y --clustered y"
    vg_options: "--autobackup y --shared"
  with_items: 
    - { vg: 'fileio_cluster_vg', pvs: '/dev/mapper/otusFileio' }
    - { vg: 'block_cluster_vg', pvs: '/dev/mapper/otusBlock' }
    - { vg: 'ramdisk_cluster_vg', pvs: '/dev/mapper/otusRamdisk' }
  when: "ansible_hostname in 'pcs-01'"

- name: Wait a little
  pause:
    seconds: 10

- name: start lock manager for shared
  ansible.builtin.command: "vgchange --lockstart {{ item.vg }}"
  with_items: 
    - { vg: 'fileio_cluster_vg' }
    - { vg: 'block_cluster_vg' }
    - { vg: 'ramdisk_cluster_vg' }
  when: "ansible_hostname in ['pcs-02','pcs-03']"

- name: Wait a little
  pause:
    seconds: 10

# lvcreate -l 100%FREE -n cluster_lv cluster_vg
- name: Create a logical volume the size of fileio
  community.general.lvol:
    vg: "{{ item.vg }}"
    lv: "{{ item.lv }}"
    size: "{{ item.size }}"
    opts: --activate sy
  with_items: 
    - { vg: 'fileio_cluster_vg', lv: 'file0_cluster_lv', size: '100%FREE' }
    - { vg: 'block_cluster_vg', lv: 'block0_cluster_lv', size: '100%FREE' }
    - { vg: 'ramdisk_cluster_vg', lv: 'ram0_cluster_lv', size: '100%FREE' }
  when: "ansible_hostname in 'pcs-01'"

- name: Wait a little
  pause:
    seconds: 10