---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ ansible_hostname }}.{{ domain }}"

- name: Add my own IP address to /etc/hosts instead localhost
  ansible.builtin.replace:
    path: "/etc/hosts"
    regexp: '^127\.0\.0\.1(\s+){{ ansible_hostname }}(\s+){{ ansible_hostname }}.*'
    replace: "{{ ansible_host }} {{ ansible_hostname }}.{{ domain }} {{ ansible_hostname }}"

- name: Add pcs-01 to /etc/hosts
  ansible.builtin.lineinfile:
    path: "/etc/hosts"
    state: present
    line: "{{ ip_address['pcs-01'] }} pcs-01.{{ domain }} pcs-01"

- name: Add pcs-02 to /etc/hosts
  ansible.builtin.lineinfile:
    path: "/etc/hosts"
    state: present
    line: "{{ ip_address['pcs-02'] }} pcs-02.{{ domain }} pcs-02"

- name: Add pcs-03 to /etc/hosts
  ansible.builtin.lineinfile:
    path: "/etc/hosts"
    state: present
    line: "{{ ip_address['pcs-03'] }} pcs-03.{{ domain }} pcs-03"

- name: Redhat OS
  block:

  - name: Allow cluster processes on SELinux
    ansible.builtin.seboolean:
      name: daemons_enable_cluster_mode
      state: yes
      persistent: yes

  when: ansible_os_family == "RedHat"
  
- name: Enable and start pcsd service
  ansible.builtin.systemd:
    name: pcsd
    state: restarted
    enabled: true

- name: Set password for local hacluster user
  ansible.builtin.user:
    name: "hacluster"
    password: "{{ pcs_password | string | password_hash('sha512') }}" 
    state: present
    update_password: always
    create_home: yes
  notify: "restart pcsd"