---
- name: Debian OS
  block:

  ## dnf install glibc-langpack-ru -y
  #- name: Installing Locale ru-RU
  #  ansible.builtin.apt:
  #    name:
  #      - glibc-langpack-ru
  #    state: present

  # apt install chrony -y
  - name: Installing Chrony Debian
    ansible.builtin.apt:
      name:
        - chrony
      state: present
      update_cache: yes

  # systemctl enable chrony --now
  - name: Start Chrony Service Debian
    ansible.builtin.systemd:
      name: chrony
      state: started
      enabled: yes

  # timedatectl set-timezone Europe/Moscow
  - name: Set timezone to Europe/Moscow
    community.general.timezone:
      name: Europe/Moscow
    notify: Restart Chrony Debian

  when: ansible_os_family == "Debian"

- name: Redhat OS
  block:

  ## dnf install glibc-langpack-ru -y
  #- name: Installing Locale ru-RU
  #  ansible.builtin.dnf:
  #    name:
  #      - glibc-langpack-ru
  #    state: present

  # dnf install chrony -y
  - name: Installing Chrony RedHat
    ansible.builtin.dnf:
      name:
        - chrony
      state: present

  # systemctl enable chronyd --now
  - name: Start Chronyd Service RedHat
    ansible.builtin.systemd:
      name: chronyd
      state: started
      enabled: yes

  # timedatectl set-timezone Europe/Moscow
  - name: Set timezone to Europe/Moscow
    community.general.timezone:
      name: Europe/Moscow
    notify: Restart Chronyd RedHat

  when: ansible_os_family == "RedHat"
